-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DMs_Locacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DMs_Locacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DMs_Locacao` DEFAULT CHARACTER SET utf8 ;
USE `DMs_Locacao` ;

-- -----------------------------------------------------
-- Table `DMs_Locacao`.`Dim_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DMs_Locacao`.`Dim_data` ;

CREATE TABLE IF NOT EXISTS `DMs_Locacao`.`Dim_data` (
  `idDim_data` INT NOT NULL,
  `dia` INT NULL DEFAULT NULL,
  `mes` INT NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDim_data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DMs_Locacao`.`Dim_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DMs_Locacao`.`Dim_veiculo` ;

CREATE TABLE IF NOT EXISTS `DMs_Locacao`.`Dim_veiculo` (
  `idDim_veiculo` INT NOT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `fabricante` VARCHAR(45) NULL DEFAULT NULL,
  `combustivel` VARCHAR(45) NULL DEFAULT NULL,
  `ano` YEAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idDim_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DMs_Locacao`.`Dim_manutencao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DMs_Locacao`.`Dim_manutencao` ;

CREATE TABLE IF NOT EXISTS `DMs_Locacao`.`Dim_manutencao` (
  `idDim_manutencao` INT NOT NULL,
  `servico_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `custo` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_retorno` DATE NULL DEFAULT NULL,
  `data_conclusao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idDim_manutencao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DMs_Locacao`.`Fato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DMs_Locacao`.`Fato` ;

CREATE TABLE IF NOT EXISTS `DMs_Locacao`.`Fato` (
  `idFato` INT NOT NULL,
  `Dim_data_idDim_data` INT NOT NULL,
  `Dim_veiculo_idDim_veiculo` INT NOT NULL,
  `Dim_manutencao_idDim_manutencao` INT NOT NULL,
  `qtd_dias_manutencao` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idFato`, `Dim_data_idDim_data`, `Dim_veiculo_idDim_veiculo`, `Dim_manutencao_idDim_manutencao`),
  INDEX `fk_Fato_Dim_data2_idx` (`Dim_data_idDim_data` ASC) VISIBLE,
  INDEX `fk_Fato_Dim_veiculo2_idx` (`Dim_veiculo_idDim_veiculo` ASC) VISIBLE,
  INDEX `fk_Fato_Dim_manutencao1_idx` (`Dim_manutencao_idDim_manutencao` ASC) VISIBLE,
  CONSTRAINT `fk_Fato_Dim_data2`
    FOREIGN KEY (`Dim_data_idDim_data`)
    REFERENCES `DMs_Locacao`.`Dim_data` (`idDim_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dim_veiculo2`
    FOREIGN KEY (`Dim_veiculo_idDim_veiculo`)
    REFERENCES `DMs_Locacao`.`Dim_veiculo` (`idDim_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dim_manutencao1`
    FOREIGN KEY (`Dim_manutencao_idDim_manutencao`)
    REFERENCES `DMs_Locacao`.`Dim_manutencao` (`idDim_manutencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
